### PR TITLE
Add UAA support to gogobosh

### PR DESCRIPTION
**Pull request by srbry**
This pull requests is to add uaa as a possible auth option to gogobosh. Using the /info endpoint the client will auto detect if it should be using basic or uaa authentication.

Minimal braking changes have been attempted however as getting a uaa token can return an error the NewClient() function now returns a client and error.

All testing as also been converted to using the same testing methodologies as in go-cfclient as ghttpd didn't seem to support oath.

### CODE REVIEW

**Comment by jimconner** [comment]
Pure awesomeness!!

**Comment by thelangley** [comment]
this is amazing, thanks

**Comment by jhunt** [comment]
LGTM

**Comment by jhunt** [comment]
Thanks!

**Comment by mehrotra-prateek** [comment]
this is great.

**Pull request merged**
